# Generated by Django 6.0.1 on 2026-01-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
